{% set name = "rapidpe-rift-pipe" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidpe_rift_pipe-{{ version }}.tar.gz
  sha256: 89decff1ed8dcd100252dfcc901f0dae89bd3b59a0836b2949c7aac428475e02

build:
  entry_points:
    - rapidpe-rift-pipe = rapidpe_rift_pipe.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - matplotlib-base
    - h5py
    - tabulate
    - lalsuite
    - gstlal
    - rift >=0.0.15.7,<0.0.15.9
    - rapid-pe >=0.1.0,<0.2.0

test:
  imports:
    - rapidpe_rift_pipe
  commands:
    - pip check
    - rapidpe-rift-pipe --help
  requires:
    - pip
    # HACK: Something is wrong with pytables, which we don't even use but a
    #       dependency does, so I'm pinning this to an older version
    - pytables ==3.7.0

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe-rift-pipe
  summary: Pipeline for running RapidPE and RIFT parameter estimation codes
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - dwysocki
